# Generated by Django 3.1 on 2020-09-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetupprofit',
            name='euro_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.eurocountry', verbose_name='Euro Country'),
        ),
        migrations.AlterField(
            model_name='usersetupprofit',
            name='uk_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.ukrange', verbose_name='UK Area'),
        ),
    ]
