# Generated by Django 3.1 on 2020-12-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersetupprofit',
            options={'ordering': ('user', 'is_uk', 'uk_area', 'euro_area'), 'verbose_name': 'Profit Setup'},
        ),
    ]
