# Generated by Django 3.1 on 2020-09-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='', max_length=4, unique=True, verbose_name='Code'),
        ),
    ]
