# Generated by Django 3.1 on 2020-09-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20200909_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='ServiceName'),
        ),
        migrations.AlterUniqueTogether(
            name='servicetype',
            unique_together={('name', 'company')},
        ),
    ]
