# Generated by Django 3.1 on 2020-09-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_pricelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
