# Generated by Django 3.1 on 2020-09-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20200909_1240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='europrice',
            unique_together={('company', 'country')},
        ),
    ]
