# Generated by Django 3.1 on 2020-09-21 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0004_delete_pricelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Basic Price')),
                ('custom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Custom')),
                ('euro_area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quote.eurocountry', verbose_name='Euro Country')),
                ('uk_area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quote.ukrange', verbose_name='UK Area')),
            ],
            options={
                'verbose_name': 'Price Sheet',
                'db_table': 'q_price_sheet',
            },
        ),
    ]
