# Generated by Django 3.1 on 2020-09-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20200909_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zonename',
            unique_together={('company', 'zone_name')},
        ),
    ]
