# Generated by Django 3.1 on 2020-09-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
    ]
