# Generated by Django 3.1 on 2020-09-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20200909_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zonesurcharge',
            unique_together={('company', 'service_type', 'zone')},
        ),
    ]
