# Generated by Django 3.1 on 2020-09-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_auto_20200909_1514'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zonedetail',
            unique_together={('company', 'zone', 'begin')},
        ),
    ]
