# Generated by Django 3.1 on 2020-09-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_pricelist_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonename',
            name='belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.ukrange', verbose_name='Belong UK Range'),
        ),
    ]
