# Generated by Django 3.1 on 2020-09-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20200909_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='europrice',
            name='minimum_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='minimum_charge(PerItem)'),
        ),
    ]
