# Generated by Django 3.1 on 2020-09-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_zonename_belong'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersetupprofit',
            unique_together=set(),
        ),
    ]
