# Generated by Django 3.1 on 2020-09-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_europrice_minimum_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='minimum_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Minimum Charge'),
        ),
    ]
