# Generated by Django 3.1 on 2020-09-25 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0008_auto_20200924_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetupprofit',
            name='euro_area',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.eurocountry', verbose_name='Euro Country'),
        ),
        migrations.AlterField(
            model_name='usersetupprofit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersetupprofit',
            name='uk_area',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.ukrange', verbose_name='UK Area'),
        ),
        migrations.AlterUniqueTogether(
            name='usersetupprofit',
            unique_together={('user', 'is_uk', 'uk_area', 'euro_area')},
        ),
    ]
