# Generated by Django 3.1 on 2020-09-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0010_auto_20200909_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eurocountry',
            name='country',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Country'),
        ),
    ]
