# Generated by Django 3.1 on 2020-09-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_auto_20200909_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='minimum_charge',
        ),
    ]
