# Generated by Django 3.1 on 2020-09-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profit_percent',
            field=models.BooleanField(choices=[(0, 'By Fix Amount'), (1, 'By Percent')], default=0, verbose_name='Profit Mode'),
        ),
    ]
