# Generated by Django 3.1 on 2020-10-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotemailgroup',
            name='desc',
            field=models.CharField(max_length=20, verbose_name='Description'),
        ),
    ]
