# Generated by Django 3.1 on 2020-08-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_role',
            field=models.IntegerField(blank=True, default='0', verbose_name='Staff_role'),
        ),
    ]
