# Generated by Django 3.1 on 2020-10-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201013_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotemailgroup',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
    ]
