# Generated by Django 3.1 on 2020-08-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200817_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_role',
            field=models.CharField(blank=True, max_length=10, verbose_name='Staff_row'),
        ),
    ]
