# Generated by Django 3.1 on 2020-08-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200818_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_role',
            field=models.CharField(blank=True, max_length=10, verbose_name='Staff_role'),
        ),
    ]
