# Generated by Django 3.1 on 2020-08-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200819_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_role',
            field=models.CharField(blank=True, default='OPERATOR', max_length=10, verbose_name='Staff_role'),
        ),
    ]
