# Generated by Django 3.1 on 2020-11-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
        ('users', '0005_auto_20201109_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='to_company', to='quote.company', verbose_name='Favorite Company'),
        ),
    ]
