# Generated by Django 3.1 on 2020-11-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_favorite_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='euro_fix_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Euro Fix Amount'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='euro_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Euro Profit Percent'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uk_fix_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='UK Fix Amount'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uk_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='UK Profit Percent'),
        ),
    ]
