# Generated by Django 3.1 on 2020-12-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201109_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__id'], 'verbose_name': 'User Profile'},
        ),
    ]
