# Generated by Django 3.1.11 on 2021-05-18 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlcCompanyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Company Name')),
                ('telephone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='telephone')),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='email')),
                ('contact', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='contact')),
                ('remark', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='remark')),
                ('is_used', models.BooleanField(default=True, verbose_name='is_used')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_flc_company', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'flc_company',
                'db_table': 'flc_company',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='FLCContainModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_1984', models.CharField(default='', max_length=4, unique=True, verbose_name='code_1984')),
                ('code_1995', models.CharField(default='', max_length=4, verbose_name='code_1995')),
                ('name', models.CharField(default='GB', max_length=40, verbose_name='contain name')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_flc_contain', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'flc_contain',
                'db_table': 'flc_contain',
                'ordering': ['code_1984'],
                'unique_together': {('code_1984',)},
            },
        ),
        migrations.CreateModel(
            name='FLCPortModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(default='GB', max_length=2, verbose_name='country')),
                ('port_code', models.CharField(default='', max_length=3, unique=True, verbose_name='port_code')),
                ('port_name', models.CharField(default='', max_length=100, verbose_name='port_name')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_flc_port', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'flc_port',
                'db_table': 'flc_port',
                'ordering': ['country', 'port_code'],
                'unique_together': {('port_code',)},
            },
        ),
        migrations.CreateModel(
            name='FLCPriceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(blank=True, default='', max_length=100, verbose_name='address')),
                ('destination_type', models.CharField(blank=True, default='', max_length=10, verbose_name='address_type')),
                ('begin_date', models.DateField(blank=True, default=django.utils.timezone.localdate, verbose_name='begin_date')),
                ('expire_date', models.DateField(blank=True, default=django.utils.timezone.localdate, verbose_name='expire_date')),
                ('date_type', models.CharField(choices=[('Pickup Date', 'Pickup Date'), ('ETA Date', 'ETA Date')], max_length=20, verbose_name='date_type')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='price')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('company_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flc_price_company', to='flc.flccompanymodel', to_field='code', verbose_name='company')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flc_price_container', to='flc.flccontainmodel', verbose_name='price_container')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_flc_price', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('port_code', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flc_price_port', to='flc.flcportmodel', to_field='port_code', verbose_name='port')),
            ],
            options={
                'verbose_name': 'flc_price_list',
                'db_table': 'flc_price_list',
                'ordering': ['company_code', 'port_code', 'destination', 'container', '-begin_date'],
                'unique_together': {('company_code', 'port_code', 'destination_type', 'destination', 'container', 'begin_date')},
            },
        ),
        migrations.CreateModel(
            name='FLCPostcodeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='postcode')),
                ('county', models.CharField(db_index=True, max_length=50, null=True, verbose_name='county')),
                ('district', models.CharField(db_index=True, max_length=50, null=True, verbose_name='district')),
                ('country', models.CharField(max_length=20, null=True, verbose_name='country')),
                ('postcode_area', models.CharField(max_length=8, verbose_name='postcode_area')),
                ('postcode_district', models.CharField(max_length=8, verbose_name='postcode_district')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=14, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=14, verbose_name='longitude')),
                ('easting', models.DecimalField(blank=True, decimal_places=0, max_digits=14, verbose_name='easting')),
                ('north', models.DecimalField(blank=True, decimal_places=0, max_digits=14, verbose_name='north')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_uk_postcode', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'flc_uk_postcode',
                'db_table': 'flc_uk_postcode',
                'ordering': ['postcode', 'county'],
                'unique_together': {('postcode',)},
            },
        ),
        migrations.CreateModel(
            name='FlcFuelChargeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='begin_date')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='expire_date')),
                ('fuel_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='fuel_charge')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('company_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flc_company_code', to='flc.flccompanymodel', to_field='code', verbose_name='company')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_flc_fuel_surcharge', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'flc_fuel_surcharge',
                'db_table': 'flc_fuel_surcharge',
                'ordering': ('company_code', '-begin_date'),
                'unique_together': {('company_code', 'begin_date')},
            },
        ),
    ]
