# Generated by Django 3.1.11 on 2021-05-18 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDetailModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(default='', max_length=50, verbose_name='Area Name')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_area_detail', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Lcl Zone Area',
                'db_table': 'lcl_zone_area',
            },
        ),
        migrations.CreateModel(
            name='LclCollectAreaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=5, unique=True, verbose_name='Code')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('telephone', models.CharField(default='', max_length=100, null=True, verbose_name='telephone')),
                ('email', models.CharField(default='', max_length=100, null=True, verbose_name='email')),
                ('contact', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='contact')),
                ('sort_num', models.IntegerField(default=0, verbose_name='sort_by')),
                ('remark', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='remark')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_lcl_warehouse', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'lcl_collect_area',
                'db_table': 'lcl_collect_area',
            },
        ),
        migrations.CreateModel(
            name='LclCompanyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Company Name')),
                ('telephone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='telephone')),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='email')),
                ('contact', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='contact')),
                ('remark', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='remark')),
                ('is_used', models.BooleanField(default=True, verbose_name='is_used')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_lcl_company', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Lcl Company',
                'db_table': 'lcl_company',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LclZoneModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(default='', max_length=10, verbose_name='Zone_name')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclcompanymodel', to_field='code', verbose_name='Company Name')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_lcl_zone', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'lcl_zone',
                'db_table': 'lcl_zone',
            },
        ),
        migrations.CreateModel(
            name='ZoneChargeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_minimum', models.IntegerField(default=0, verbose_name='Weight Minimum')),
                ('weight_maximum', models.IntegerField(default=0, verbose_name='Weight Maximum')),
                ('cbm_minimum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='CBM Minimum')),
                ('cbm_maximum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='CBM Maximum')),
                ('basic_price', models.DecimalField(blank=True, decimal_places=9, default=0, max_digits=14, verbose_name='Base Price')),
                ('service_type', models.CharField(default='', max_length=20, verbose_name='Service Type')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('collect_area', models.ForeignKey(default='FELIX', on_delete=django.db.models.deletion.CASCADE, to='lcl.lclcollectareamodel', to_field='code', verbose_name='Collection Area')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_zone_charge', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclzonemodel', verbose_name='Zone Name')),
            ],
            options={
                'verbose_name': 'Lcl Zone Charge',
                'db_table': 'lcl_zone_charge',
            },
        ),
        migrations.CreateModel(
            name='LclZoneExtraDetailModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.CharField(default='', max_length=10, verbose_name='Begin')),
                ('end', models.CharField(default='', max_length=10, verbose_name='End')),
                ('charge_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='charge Price')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_lcl_zone_extra_detail', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Lcl Zone Extra',
                'db_table': 'lcl_zone_extra',
            },
        ),
        migrations.CreateModel(
            name='LclZoneDetailModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.CharField(default='', max_length=10, verbose_name='Begin')),
                ('end', models.CharField(default='', max_length=10, verbose_name='End')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_lcl_zone_detail', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclzonemodel', verbose_name='Zone Name')),
            ],
            options={
                'verbose_name': 'Lcl Zone Detail',
                'db_table': 'lcl_zone_detail',
            },
        ),
        migrations.CreateModel(
            name='LclProfitViaAreaDetailModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('via_area', models.CharField(default='', max_length=50, verbose_name='via_area')),
                ('service_type', models.CharField(default='', max_length=20, verbose_name='Service Type')),
                ('fix_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='fix_price')),
                ('percent_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='percent_price')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_lcl_profit', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'lcl_profit',
                'db_table': 'lcl_profit',
            },
        ),
        migrations.CreateModel(
            name='LclAreaDetailModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.CharField(default='', max_length=10, verbose_name='Begin')),
                ('end', models.CharField(default='', max_length=10, verbose_name='End')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.areadetailmodel', verbose_name='Area Name')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_lcl_area_detail', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Lcl Area Detail',
                'db_table': 'lcl_area_detail',
            },
        ),
        migrations.AddField(
            model_name='areadetailmodel',
            name='zone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclzonemodel', verbose_name='Zone Name'),
        ),
        migrations.CreateModel(
            name='LclFuelChargeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='begin_date')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='expire_date')),
                ('fuel_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='fuel_charge')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcl_company_code', to='lcl.lclcompanymodel', to_field='code', verbose_name='company')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_lcl_fuel_surcharge', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'lcl_fuel_surcharge',
                'db_table': 'lcl_fuel_surcharge',
                'ordering': ('company_code', '-begin_date'),
                'unique_together': {('company_code', 'begin_date')},
            },
        ),
    ]
