# Generated by Django 3.1 on 2020-12-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LclZone24',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(default='', max_length=10, verbose_name='Zone24_name')),
            ],
            options={
                'verbose_name': 'lcl_zone_24',
                'db_table': 'lcl_zone_24',
            },
        ),
        migrations.CreateModel(
            name='LclZone48',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(default='', max_length=10, verbose_name='Zone48_name')),
            ],
            options={
                'verbose_name': 'lcl_zone_48',
                'db_table': 'lcl_zone_48',
            },
        ),
        migrations.CreateModel(
            name='Zone48Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.CharField(default='', max_length=10, verbose_name='Begin')),
                ('end', models.CharField(default='', max_length=10, verbose_name='End')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclzone48', verbose_name='Zone48 Name')),
            ],
            options={
                'verbose_name': 'Zone 48 Detail',
                'db_table': 'lcl_zone_48detail',
            },
        ),
        migrations.CreateModel(
            name='Zone24Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.CharField(default='', max_length=10, verbose_name='Begin')),
                ('end', models.CharField(default='', max_length=10, verbose_name='End')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclzone24', verbose_name='Zone24 Name')),
            ],
            options={
                'verbose_name': 'Zone 24 Detail',
                'db_table': 'lcl_zone_24detail',
            },
        ),
    ]
