# Generated by Django 3.1 on 2020-12-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lclzone24',
            name='op_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
        migrations.AddField(
            model_name='lclzone48',
            name='op_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
        migrations.AddField(
            model_name='zone24detail',
            name='op_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
        migrations.AddField(
            model_name='zone48detail',
            name='op_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
    ]
