# Generated by Django 3.1 on 2020-12-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0002_auto_20201214_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lclzone24',
            name='op_last_update',
        ),
        migrations.RemoveField(
            model_name='lclzone48',
            name='op_last_update',
        ),
        migrations.RemoveField(
            model_name='zone24detail',
            name='op_last_update',
        ),
        migrations.RemoveField(
            model_name='zone48detail',
            name='op_last_update',
        ),
    ]
