# Generated by Django 3.1 on 2020-12-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0003_auto_20201214_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_item', models.CharField(default='', max_length=50, verbose_name='Item')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('unit_description', models.CharField(default='', max_length=40, verbose_name='Unit')),
                ('remark', models.CharField(default='', max_length=100, verbose_name='Remark')),
            ],
            options={
                'verbose_name': 'General Charge',
                'db_table': 'lcl_general_charge',
            },
        ),
        migrations.CreateModel(
            name='Charge48',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum', models.IntegerField(default=0, verbose_name='Minimum')),
                ('maximum', models.IntegerField(default=0, verbose_name='maximum')),
                ('basic_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('plus_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclzone48', verbose_name='Zone48 Name')),
            ],
            options={
                'verbose_name': '48Hour Charge',
                'db_table': 'lcl_charge48',
            },
        ),
        migrations.CreateModel(
            name='Charge24',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum', models.IntegerField(default=0, verbose_name='Minimum')),
                ('maximum', models.IntegerField(default=0, verbose_name='maximum')),
                ('basic_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('plus_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclzone24', verbose_name='Zone24 Name')),
            ],
            options={
                'verbose_name': '24Hour Charge',
                'db_table': 'lcl_charge24',
            },
        ),
    ]
