# Generated by Django 3.1 on 2020-12-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0004_charge24_charge48_generalcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge24',
            name='unit_description',
            field=models.CharField(default='KILOS', max_length=20, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='charge48',
            name='unit_description',
            field=models.CharField(default='CBB', max_length=20, verbose_name='Unit'),
        ),
    ]
