# Generated by Django 3.1 on 2020-12-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0005_auto_20201215_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge48',
            name='postcode_description',
            field=models.CharField(default='', max_length=200, verbose_name='Postcode description'),
        ),
    ]
