# Generated by Django 3.1 on 2020-12-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0006_charge48_postcode_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge24',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='charge48',
            name='zone',
        ),
        migrations.DeleteModel(
            name='GeneralCharge',
        ),
        migrations.RemoveField(
            model_name='zone24detail',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='zone48detail',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Charge24',
        ),
        migrations.DeleteModel(
            name='Charge48',
        ),
        migrations.DeleteModel(
            name='LclZone24',
        ),
        migrations.DeleteModel(
            name='LclZone48',
        ),
        migrations.DeleteModel(
            name='Zone24Detail',
        ),
        migrations.DeleteModel(
            name='Zone48Detail',
        ),
    ]
