# Generated by Django 3.1 on 2020-12-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lcl', '0007_auto_20201215_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='LclCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(default='', max_length=100, null=True, verbose_name='Company Name')),
                ('fuel_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Fuel Charge')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
            ],
            options={
                'verbose_name': 'Lcl Company',
                'db_table': 'lcl_company',
            },
        ),
        migrations.CreateModel(
            name='LclZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(default='', max_length=10, verbose_name='Zone_name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclcompany', to_field='code', verbose_name='Company Name')),
            ],
            options={
                'verbose_name': 'lcl_zone',
                'db_table': 'lcl_zone',
            },
        ),
        migrations.CreateModel(
            name='ZoneCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum', models.IntegerField(default=0, verbose_name='Minimum')),
                ('maximum', models.IntegerField(default=0, verbose_name='maximum')),
                ('unit_description', models.CharField(default='CBB', max_length=20, verbose_name='Unit')),
                ('basic_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('service_type', models.CharField(default='', max_length=200, verbose_name='Service Type')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclzone', verbose_name='Zone Name')),
            ],
            options={
                'verbose_name': 'Lcl Zone Charge',
                'db_table': 'lcl_zone_charge',
            },
        ),
        migrations.CreateModel(
            name='LclZoneDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.CharField(default='', max_length=10, verbose_name='Begin')),
                ('end', models.CharField(default='', max_length=10, verbose_name='End')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclzone', verbose_name='Zone24 Name')),
            ],
            options={
                'verbose_name': 'Lcl Zone Detail',
                'db_table': 'lcl_zone_detail',
            },
        ),
    ]
