# Generated by Django 3.1 on 2020-12-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0008_lclcompany_lclzone_lclzonedetail_zonecharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lclcompany',
            name='op_last_update',
        ),
    ]
