# Generated by Django 3.1 on 2020-12-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0009_remove_lclcompany_op_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='lclcompany',
            name='op_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
        migrations.AddField(
            model_name='lclzone',
            name='op_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
        migrations.AddField(
            model_name='zonecharge',
            name='op_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
    ]
