# Generated by Django 3.1 on 2020-12-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0010_auto_20201217_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lclcompany',
            name='op_last_update',
        ),
    ]
