# Generated by Django 3.1 on 2020-12-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0011_remove_lclcompany_op_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lclzonedetail',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclzone', verbose_name='Zone Name'),
        ),
    ]
