# Generated by Django 3.1 on 2020-12-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0012_auto_20201217_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='lclcompany',
            name='op_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
    ]
