# Generated by Django 3.1 on 2020-12-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0013_lclcompany_op_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lclzone',
            name='op_last_update',
        ),
    ]
