# Generated by Django 3.1 on 2020-12-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0014_remove_lclzone_op_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonecharge',
            name='maximum',
        ),
        migrations.RemoveField(
            model_name='zonecharge',
            name='minimum',
        ),
        migrations.RemoveField(
            model_name='zonecharge',
            name='unit_description',
        ),
        migrations.AddField(
            model_name='zonecharge',
            name='cbm_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='CBM Maximum'),
        ),
        migrations.AddField(
            model_name='zonecharge',
            name='cbm_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='CBM Minimum'),
        ),
        migrations.AddField(
            model_name='zonecharge',
            name='weight_maximum',
            field=models.IntegerField(default=0, verbose_name='Weight Maximum'),
        ),
        migrations.AddField(
            model_name='zonecharge',
            name='weight_minimum',
            field=models.IntegerField(default=0, verbose_name='Weight Minimum'),
        ),
        migrations.AlterField(
            model_name='zonecharge',
            name='basic_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, verbose_name='Base Price'),
        ),
    ]
