# Generated by Django 3.1 on 2020-12-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0015_auto_20201218_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonecharge',
            name='basic_price',
            field=models.DecimalField(blank=True, decimal_places=9, default=0, max_digits=14, verbose_name='Base Price'),
        ),
    ]
