# Generated by Django 3.1 on 2021-01-25 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0016_auto_20201218_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(default='', max_length=50, verbose_name='Area Name')),
                ('zone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.lclzone', verbose_name='Zone Name')),
            ],
            options={
                'verbose_name': 'Lcl Zone Area',
                'db_table': 'lcl_zone_area',
            },
        ),
    ]
