# Generated by Django 3.1 on 2021-01-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcl', '0017_areadetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LclAreaDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.CharField(default='', max_length=10, verbose_name='Begin')),
                ('end', models.CharField(default='', max_length=10, verbose_name='End')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcl.areadetail', verbose_name='Area Name')),
            ],
            options={
                'verbose_name': 'Lcl Area Detail',
                'db_table': 'lcl_area_detail',
            },
        ),
    ]
