# Generated by Django 3.1.11 on 2021-05-18 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateItemPriceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_code', models.CharField(default='', max_length=5, unique=True, verbose_name='fee_code')),
                ('en_name', models.CharField(default='', max_length=50, verbose_name='en_name')),
                ('cn_name', models.CharField(default='', max_length=50, verbose_name='cn_name')),
                ('unit', models.CharField(default='', max_length=20, verbose_name='unit')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='rate')),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='minimum_charge')),
                ('fee_type', models.IntegerField(default='0', verbose_name='fee_type')),
                ('remark', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='remark')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_private_item_price', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'ocean_private_item_price',
                'db_table': 'ocean_private_item_price',
                'ordering': ['en_name'],
            },
        ),
        migrations.CreateModel(
            name='PostcodePriceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(default='', max_length=50, unique=True, verbose_name='en_name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='price')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_postcode_type', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'ocean_postcode_price',
                'db_table': 'ocean_postcode_price',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='PostcodeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin_code', models.CharField(default='', max_length=10, unique=True, verbose_name='begin_code')),
                ('end_code', models.CharField(default='', max_length=10, verbose_name='end_code')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_postcode_detail', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('postcode_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocean.postcodepricemodel', verbose_name='postcode_type')),
            ],
            options={
                'verbose_name': 'ocean_postcode_detail',
                'db_table': 'ocean_postcode_detail',
                'ordering': ['postcode_type', 'begin_code'],
            },
        ),
        migrations.CreateModel(
            name='LondonPostcodeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin_code', models.CharField(default='', max_length=10, unique=True, verbose_name='begin_code')),
                ('end_code', models.CharField(default='', max_length=10, verbose_name='end_code')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_postcode_london', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'ocean_postcode_london',
                'db_table': 'ocean_postcode_london',
                'ordering': ['begin_code'],
            },
        ),
        migrations.CreateModel(
            name='FbaItemPriceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_code', models.CharField(default='', max_length=5, unique=True, verbose_name='fee_code')),
                ('en_name', models.CharField(default='', max_length=50, verbose_name='en_name')),
                ('cn_name', models.CharField(default='', max_length=50, verbose_name='cn_name')),
                ('unit', models.CharField(default='', max_length=20, verbose_name='unit')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='rate')),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='minimum_charge')),
                ('fee_type', models.IntegerField(default='0', verbose_name='fee_type')),
                ('remark', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='remark')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_fba_pallet_price', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'ocean_fba_pallet_price',
                'db_table': 'ocean_fba_item_price',
                'ordering': ['en_name', 'fee_code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, verbose_name='exchange_rate')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_exchange_rate', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'ocean_exchange_rate',
                'db_table': 'ocean_exchange_rate',
            },
        ),
        migrations.CreateModel(
            name='CabinetItemPriceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_code', models.CharField(default='', max_length=5, unique=True, verbose_name='fee_code')),
                ('en_name', models.CharField(default='', max_length=50, verbose_name='en_name')),
                ('cn_name', models.CharField(default='', max_length=50, verbose_name='cn_name')),
                ('unit', models.CharField(default='', max_length=20, verbose_name='unit')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='rate')),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='minimum_charge')),
                ('fee_type', models.IntegerField(default='0', verbose_name='fee_type')),
                ('remark', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='remark')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_cabinet_item_price', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'ocean_cabinet_item_price',
                'db_table': 'ocean_cabinet_item_price',
                'ordering': ['en_name'],
            },
        ),
        migrations.CreateModel(
            name='AmazonWarehouseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fba_code', models.CharField(default='', max_length=20, unique=True, verbose_name='fba_code')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='address')),
                ('city', models.CharField(default='', max_length=20, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='state')),
                ('postcode', models.CharField(default='', max_length=10, verbose_name='postcode')),
                ('is_used', models.BooleanField(default=True, verbose_name='is_used')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_ocean_amazon', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'ocean_amazon_warehouse',
                'db_table': 'ocean_amazon_warehouse',
                'ordering': ['fba_code'],
            },
        ),
        migrations.CreateModel(
            name='AmazonPriceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('whole_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='whole_price')),
                ('pallet_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='pallet_price')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('amazon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_warehouse_id', to='ocean.amazonwarehousemodel', verbose_name='amazon_id')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_amazon_price', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'ocean_whole_price',
                'db_table': 'ocean_amazon_price',
                'ordering': ['amazon'],
            },
        ),
        migrations.CreateModel(
            name='OceanPortModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(default='GB', max_length=2, verbose_name='country')),
                ('port_code', models.CharField(default='', max_length=3, unique=True, verbose_name='port_code')),
                ('port_name', models.CharField(default='', max_length=100, verbose_name='port_name')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_ocean_port', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'ocean_port',
                'db_table': 'ocean_port',
                'ordering': ['country', 'port_code'],
                'unique_together': {('port_code',)},
            },
        ),
        migrations.CreateModel(
            name='ContainModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=4, unique=True, verbose_name='code')),
                ('name', models.CharField(default='GB', max_length=100, verbose_name='contain name')),
                ('max_volume', models.IntegerField(default='0', verbose_name='max_volume')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_ocean_container', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'ocean_container',
                'db_table': 'ocean_container',
                'ordering': ['code'],
                'unique_together': {('code',)},
            },
        ),
    ]
