# Generated by Django 3.1.11 on 2021-05-18 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sku.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuFileUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='C:\\DCG\\GitHub\\warehouse\\media', validators=[sku.validators.validate_file_extension])),
                ('file_name', models.CharField(default='', max_length=300, verbose_name='File Name')),
                ('is_db', models.IntegerField(choices=[(1, 'OK'), (0, 'Waiting')], default=0, verbose_name='To DB')),
                ('upload_date', models.DateTimeField(auto_now=True, verbose_name='Upload')),
                ('db_date', models.DateTimeField(blank=True, null=True, verbose_name='DB Operate')),
                ('custom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Custom')),
            ],
            options={
                'verbose_name': 'SKU File',
                'db_table': 'sku_upload',
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_no', models.CharField(default='', max_length=30, verbose_name='SKU No')),
                ('sku_name', models.CharField(default='', max_length=200, verbose_name='Produce Name')),
                ('sku_length', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Length(CM)')),
                ('sku_width', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Width(CM)')),
                ('sku_high', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='High(CM)')),
                ('sku_weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Weight(KG)')),
                ('is_ok', models.IntegerField(choices=[(1, 'OK'), (0, 'Suspend')], default=1, verbose_name='Is OK?')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('custom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Custom')),
            ],
            options={
                'verbose_name': 'SKU',
                'db_table': 'sku',
                'ordering': ['sku_no'],
                'unique_together': {('custom', 'sku_no')},
            },
        ),
    ]
