# Generated by Django 3.1 on 2020-09-11 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_no', models.CharField(default='', max_length=20, verbose_name='SKU No')),
                ('sku', models.CharField(default='', max_length=20, verbose_name='')),
                ('sku_name', models.CharField(default='', max_length=200, verbose_name='Produce Name')),
                ('sku_length', models.CharField(default='', max_length=200, verbose_name='Length(CM)')),
                ('sku_width', models.CharField(default='', max_length=200, verbose_name='Width(CM)')),
                ('sku_high', models.CharField(default='', max_length=200, verbose_name='High(CM)')),
                ('sku_weight', models.CharField(default='', max_length=200, verbose_name='Weight(KG)')),
                ('is_use', models.BooleanField(default=True)),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('custom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Custom')),
            ],
            options={
                'verbose_name': 'SKU',
                'db_table': 'sku',
            },
        ),
    ]
