# Generated by Django 3.1 on 2020-11-09 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuQuoteHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0, verbose_name='Qty.')),
                ('destination', models.CharField(default='', max_length=50, verbose_name='Destination')),
                ('basic_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Basic Price')),
                ('oversize', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='oversize')),
                ('overweight', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='overweight')),
                ('additional', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Additional')),
                ('fuel_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fuel Charge')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('custom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Custom')),
                ('favorite_company', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='suk_favorite_company', to='quote.company', verbose_name='Favorite Company')),
                ('sku', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sku.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Quote History',
                'db_table': 'sku_quote_history',
            },
        ),
        migrations.DeleteModel(
            name='SkyQuoteHistory',
        ),
    ]
