# Generated by Django 3.1 on 2020-09-21 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0, verbose_name='Qty.')),
                ('destination', models.CharField(default='', max_length=50, verbose_name='Destination')),
                ('basic_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Basic Price')),
                ('congestion', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Congestion')),
                ('additional', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Additional')),
                ('fuel_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fuel Charge')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('custom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Custom')),
                ('sku', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sku.sku', verbose_name='SKU')),
            ],
        ),
    ]
