# Generated by Django 3.1 on 2020-09-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='is_use',
            new_name='is_ok',
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='last_modify',
            new_name='last_update',
        ),
    ]
