# Generated by Django 3.1 on 2020-12-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0002_auto_20201109_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['sku_no'], 'verbose_name': 'SKU'},
        ),
        migrations.DeleteModel(
            name='SkuQuoteHistory',
        ),
    ]
