# Generated by Django 3.1 on 2020-09-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0002_quotehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteHistory',
        ),
    ]
