# Generated by Django 3.1 on 2020-09-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0003_auto_20200911_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='is_ok',
            field=models.IntegerField(choices=[(1, 'OK'), (0, 'Suspend')], default=1, verbose_name='Is OK?'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_high',
            field=models.IntegerField(blank=True, default=0, verbose_name='High(CM)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_length',
            field=models.IntegerField(blank=True, default=0, verbose_name='Length(CM)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Weight(KG)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_width',
            field=models.IntegerField(blank=True, default=0, verbose_name='Width(CM)'),
        ),
    ]
