# Generated by Django 3.1 on 2020-09-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0004_skyquotehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skyquotehistory',
            name='congestion',
        ),
        migrations.AddField(
            model_name='skyquotehistory',
            name='oversize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='oversize'),
        ),
        migrations.AddField(
            model_name='skyquotehistory',
            name='overweight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='overweight'),
        ),
    ]
