# Generated by Django 3.1 on 2020-09-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0004_auto_20200911_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku_high',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='High(CM)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Length(CM)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Width(CM)'),
        ),
    ]
