# Generated by Django 3.1 on 2020-10-01 11:05

from django.db import migrations, models
import sku.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0005_auto_20200921_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skufileupload',
            name='file',
            field=models.FileField(upload_to='C:\\DCG\\GitHub\\warehouse\\media', validators=[sku.validators.validate_file_extension]),
        ),
    ]
