# Generated by Django 3.1 on 2020-09-16 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sku', '0005_auto_20200911_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku_high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='High(CM)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Length(CM)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Weight(KG)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Width(CM)'),
        ),
        migrations.AlterUniqueTogether(
            name='sku',
            unique_together={('custom', 'sku_no')},
        ),
    ]
