# Generated by Django 3.1 on 2020-09-17 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sku', '0006_auto_20200916_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuFileUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(default='', max_length=300, verbose_name='File Name')),
                ('is_db', models.IntegerField(choices=[(1, 'OK'), (0, 'Waiting')], default=0, verbose_name='To DB')),
                ('upload_date', models.DateTimeField(auto_now=True, verbose_name='Upload')),
                ('db_date', models.DateTimeField(blank=True, verbose_name='Operate')),
                ('custom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Custom')),
            ],
            options={
                'verbose_name': 'SKU File',
                'db_table': 'sku_upload',
            },
        ),
    ]
