# Generated by Django 3.1 on 2020-09-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0007_skufileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skufileupload',
            name='db_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Operate'),
        ),
    ]
