# Generated by Django 3.1 on 2020-09-17 15:57

from django.db import migrations, models
import sku.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0008_auto_20200917_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d', validators=[sku.validators.validate_file_extension])),
            ],
        ),
        migrations.AlterField(
            model_name='skufileupload',
            name='db_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DB Operate'),
        ),
    ]
