# Generated by Django 3.1 on 2020-09-17 16:04

from django.db import migrations, models
import django.utils.timezone
import sku.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0009_auto_20200917_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='skufileupload',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='C:\\DCG\\GitHub\\warehouse\\media/upload', validators=[sku.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
