# Generated by Django 3.1.11 on 2021-05-18 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirZone24',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(default='', max_length=10, verbose_name='Zone24_name')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_air_zone24', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'air_zone_24',
                'db_table': 'air_zone_24',
            },
        ),
        migrations.CreateModel(
            name='AirZone48',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(default='', max_length=10, verbose_name='Zone48_name')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_air_zone48', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'air_zone_48',
                'db_table': 'air_zone_48',
            },
        ),
        migrations.CreateModel(
            name='Zone48Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.CharField(default='', max_length=10, verbose_name='Begin')),
                ('end', models.CharField(default='', max_length=10, verbose_name='End')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_zone48_detail', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_freight.airzone48', verbose_name='Zone48 Name')),
            ],
            options={
                'verbose_name': 'Zone 48 Detail',
                'db_table': 'air_zone_48detail',
            },
        ),
        migrations.CreateModel(
            name='Zone24Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.CharField(default='', max_length=10, verbose_name='Begin')),
                ('end', models.CharField(default='', max_length=10, verbose_name='End')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_zone24_detail', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_freight.airzone24', verbose_name='Zone24 Name')),
            ],
            options={
                'verbose_name': 'Zone 24 Detail',
                'db_table': 'air_zone_24detail',
            },
        ),
        migrations.CreateModel(
            name='GeneralCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_item', models.CharField(default='', max_length=50, verbose_name='Item')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='minimum charge')),
                ('unit_description', models.CharField(default='', max_length=40, verbose_name='Unit')),
                ('remark', models.CharField(default='', max_length=100, verbose_name='Remark')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_general_charge', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'General Charge',
                'db_table': 'air_general_charge',
            },
        ),
        migrations.CreateModel(
            name='CustomProfitRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(default='24Hours', max_length=10, verbose_name='Item_name')),
                ('volume_minimum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='volume_minimum')),
                ('volume_maximum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='volume_maximum')),
                ('fix_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='volume_maximum')),
                ('percent_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='fix profit')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_custom_profit_rate', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Air Custom Profit Rate',
                'db_table': 'air_custom_profit_rate',
            },
        ),
        migrations.CreateModel(
            name='Const',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_item', models.CharField(default='CMB24HR', max_length=10, verbose_name='Unit')),
                ('unit_change', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Change')),
                ('remark', models.CharField(default=' ', max_length=50, verbose_name='Remark')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_const', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Air Const',
                'db_table': 'air_const',
            },
        ),
        migrations.CreateModel(
            name='Charge48',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Minimum')),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='maximum')),
                ('unit_description', models.CharField(default='CBB', max_length=20, verbose_name='Unit')),
                ('basic_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Base Price')),
                ('plus_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Plus Price')),
                ('postcode_description', models.CharField(default='', max_length=200, verbose_name='Postcode description')),
                ('service', models.CharField(default='48Hours', max_length=10, verbose_name='Service')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_charge48', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_freight.airzone48', verbose_name='Zone48 Name')),
            ],
            options={
                'verbose_name': '48Hour Charge',
                'db_table': 'air_charge48',
            },
        ),
        migrations.CreateModel(
            name='Charge24',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Minimum')),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='maximum')),
                ('unit_description', models.CharField(default='KILOS', max_length=20, verbose_name='Unit')),
                ('basic_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Base Price')),
                ('plus_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Base Price')),
                ('op_last_update', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_charge24', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_freight.airzone24', verbose_name='Zone24 Name')),
            ],
            options={
                'verbose_name': '24Hour Charge',
                'db_table': 'air_charge24',
            },
        ),
    ]
