# Generated by Django 3.1 on 2020-12-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirZone24',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(default='', max_length=10, verbose_name='Zone24_name')),
            ],
            options={
                'verbose_name': 'air_zone_24',
                'db_table': 'air_zone_24',
            },
        ),
        migrations.CreateModel(
            name='AirZone48',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(default='', max_length=10, verbose_name='Zone48_name')),
            ],
            options={
                'verbose_name': 'air_zone_48',
                'db_table': 'air_zone_48',
            },
        ),
        migrations.CreateModel(
            name='GeneralCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_item', models.CharField(default='', max_length=50, verbose_name='Item')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('unit_description', models.CharField(default='', max_length=40, verbose_name='Unit')),
                ('remark', models.CharField(default='', max_length=100, verbose_name='Remark')),
            ],
            options={
                'verbose_name': 'General Charge',
                'db_table': 'air_general_charge',
            },
        ),
        migrations.CreateModel(
            name='Zone48Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.CharField(default='', max_length=10, verbose_name='Begin')),
                ('end', models.CharField(default='', max_length=10, verbose_name='End')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_freight.airzone48', verbose_name='Zone48 Name')),
            ],
            options={
                'verbose_name': 'Zone 48 Detail',
                'db_table': 'air_zone_48detail',
            },
        ),
        migrations.CreateModel(
            name='Zone24Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.CharField(default='', max_length=10, verbose_name='Begin')),
                ('end', models.CharField(default='', max_length=10, verbose_name='End')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_freight.airzone24', verbose_name='Zone24 Name')),
            ],
            options={
                'verbose_name': 'Zone 24 Detail',
                'db_table': 'air_zone_24detail',
            },
        ),
        migrations.CreateModel(
            name='Charge48',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum', models.IntegerField(default=0, verbose_name='Minimum')),
                ('maximum', models.IntegerField(default=0, verbose_name='maximum')),
                ('unit_description', models.CharField(default='CBB', max_length=20, verbose_name='Unit')),
                ('basic_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('plus_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('postcode_description', models.CharField(default='', max_length=200, verbose_name='Postcode description')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_freight.airzone48', verbose_name='Zone48 Name')),
            ],
            options={
                'verbose_name': '48Hour Charge',
                'db_table': 'air_charge48',
            },
        ),
        migrations.CreateModel(
            name='Charge24',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum', models.IntegerField(default=0, verbose_name='Minimum')),
                ('maximum', models.IntegerField(default=0, verbose_name='maximum')),
                ('unit_description', models.CharField(default='KILOS', max_length=20, verbose_name='Unit')),
                ('basic_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('plus_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Base Price')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_freight.airzone24', verbose_name='Zone24 Name')),
            ],
            options={
                'verbose_name': '24Hour Charge',
                'db_table': 'air_charge24',
            },
        ),
    ]
