# Generated by Django 3.1 on 2020-12-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_freight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcharge',
            name='minimum_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='minimum charge'),
        ),
    ]
