# Generated by Django 3.1 on 2021-01-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_freight', '0002_generalcharge_minimum_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Const',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_item', models.CharField(default='CMB24HR', max_length=10, verbose_name='Unit')),
                ('unit_change', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Change')),
                ('remark', models.CharField(default=' ', max_length=20, verbose_name='Remark')),
            ],
        ),
    ]
