# Generated by Django 3.1 on 2021-01-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_freight', '0003_const'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='const',
            options={'verbose_name': 'Air Const'},
        ),
        migrations.AlterModelTable(
            name='const',
            table='air_const',
        ),
    ]
