# Generated by Django 3.1 on 2021-01-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_freight', '0004_auto_20210119_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='const',
            name='remark',
            field=models.CharField(default=' ', max_length=50, verbose_name='Remark'),
        ),
    ]
