# Generated by Django 3.1 on 2021-01-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_freight', '0005_auto_20210119_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone48detail',
            name='service',
            field=models.CharField(default='48Hr', max_length=10, verbose_name='Service'),
        ),
    ]
