# Generated by Django 3.1 on 2021-01-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_freight', '0006_zone48detail_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone48detail',
            name='service',
        ),
        migrations.AddField(
            model_name='charge48',
            name='service',
            field=models.CharField(default='48Hr', max_length=10, verbose_name='Service'),
        ),
    ]
