# Generated by Django 3.1 on 2021-01-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_freight', '0007_auto_20210120_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge48',
            name='service',
            field=models.CharField(default='48Hours', max_length=10, verbose_name='Service'),
        ),
    ]
