# Generated by Django 3.1 on 2021-01-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_freight', '0008_auto_20210120_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProfitRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(default='24Hours', max_length=10, verbose_name='Item_name')),
                ('volume_minimum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='volume_minimum')),
                ('volume_maximum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='volume_maximum')),
                ('fix_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='fix profit')),
                ('percent_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='fix profit')),
            ],
            options={
                'verbose_name': 'Air Custom Profit Rate',
                'db_table': 'air_custom_profit_rate',
            },
        ),
    ]
