# Generated by Django 3.1 on 2021-01-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_freight', '0009_customprofitrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofitrate',
            name='fix_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='volume_maximum'),
        ),
        migrations.AlterField(
            model_name='customprofitrate',
            name='percent_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='fix profit'),
        ),
        migrations.AlterField(
            model_name='customprofitrate',
            name='volume_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='volume_maximum'),
        ),
        migrations.AlterField(
            model_name='customprofitrate',
            name='volume_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='volume_minimum'),
        ),
    ]
