# Generated by Django 3.1 on 2021-01-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_freight', '0010_auto_20210121_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge24',
            name='basic_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='charge24',
            name='maximum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='maximum'),
        ),
        migrations.AlterField(
            model_name='charge24',
            name='minimum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Minimum'),
        ),
        migrations.AlterField(
            model_name='charge24',
            name='plus_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='charge48',
            name='basic_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='charge48',
            name='maximum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='maximum'),
        ),
        migrations.AlterField(
            model_name='charge48',
            name='minimum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Minimum'),
        ),
        migrations.AlterField(
            model_name='charge48',
            name='plus_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Plus Price'),
        ),
    ]
