# Generated by Django 3.1 on 2020-08-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haulier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=100, verbose_name='Telephone')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='Email')),
                ('is_use', models.IntegerField(default=1)),
                ('op_id', models.IntegerField(default=0)),
                ('op_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Haulier',
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryref', models.CharField(default='', max_length=25)),
                ('progress', models.PositiveIntegerField(default=1)),
                ('progress_name', models.CharField(blank=True, default='', max_length=10)),
                ('position', models.CharField(default='UK', max_length=2)),
                ('remark', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('op_id', models.IntegerField(default=0)),
                ('op_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Progress_record',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(default='UK', max_length=2)),
                ('beginworktime', models.TimeField(blank=True)),
                ('overworktime', models.TimeField(blank=True)),
                ('maxslot', models.PositiveIntegerField(default='2')),
                ('maxinbound', models.PositiveIntegerField(default='0')),
                ('op_id', models.IntegerField(default=0)),
                ('op_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'WarehouseProfile',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryref', models.CharField(default='', max_length=25)),
                ('workdate', models.DateField()),
                ('slottime', models.TimeField()),
                ('vehiclereg', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('status', models.CharField(default='INBOUND', max_length=8)),
                ('progress', models.PositiveIntegerField(default=1)),
                ('havetime', models.PositiveIntegerField(default=1)),
                ('position', models.CharField(default='UK', max_length=2)),
                ('op_id', models.IntegerField(default=0)),
                ('op_datetime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('hailerid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='haulier_warehouse', to='slot.haulier')),
            ],
            options={
                'db_table': 'Warehouse',
                'unique_together': {('deliveryref',)},
            },
        ),
        migrations.CreateModel(
            name='FixWeekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(default=1)),
                ('time', models.TimeField(blank=True)),
                ('status', models.PositiveIntegerField(default=1)),
                ('op_id', models.IntegerField(default=0)),
                ('op_datetime', models.DateTimeField(auto_now=True)),
                ('Haulier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.haulier')),
            ],
            options={
                'db_table': 'Haulier_FixTime',
                'unique_together': {('Haulier', 'weekday', 'time')},
            },
        ),
    ]
