# Generated by Django 3.1 on 2020-08-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haulier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('op_user', models.CharField(default='', max_length=20)),
                ('op_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'haulier',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(default='UK', max_length=2)),
                ('maxslot', models.PositiveIntegerField()),
                ('maxinbound', models.PositiveIntegerField()),
                ('op_user', models.CharField(default='', max_length=20)),
                ('op_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'warehouse_profile',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('deliveryref', models.CharField(default='', max_length=25, primary_key=True, serialize=False)),
                ('workdate', models.DateField()),
                ('slottime', models.TimeField()),
                ('vehiclereg', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('status', models.CharField(default='INBOUND', max_length=8)),
                ('progress', models.PositiveIntegerField(default=1)),
                ('havetime', models.PositiveIntegerField(default=1)),
                ('op_user', models.CharField(default='', max_length=20)),
                ('op_datetime', models.DateTimeField(auto_now=True)),
                ('hailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.haulier')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.warehouseprofile')),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='FixWeekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(default=1)),
                ('time', models.TimeField()),
                ('status', models.PositiveIntegerField(default=1)),
                ('op_user', models.CharField(default='', max_length=20)),
                ('op_datetime', models.DateTimeField(auto_now=True)),
                ('hailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.haulier')),
            ],
            options={
                'db_table': 'fix_weekday',
            },
        ),
    ]
