# Generated by Django 3.1.11 on 2021-05-18 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Haulier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=4, unique=True, verbose_name='Code')),
                ('name', models.CharField(default='', max_length=50, null=True, verbose_name='Company Name')),
                ('contact', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Contact')),
                ('telephone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Telephone')),
                ('email', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Email')),
                ('is_use', models.IntegerField(choices=[(1, 'Normal'), (0, 'Stop')], default=1, verbose_name='Is Normal')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_haulier', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Haulier List',
                'db_table': 'Haulier',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(default='UK', max_length=10, unique=True, verbose_name='Position')),
                ('desc', models.CharField(default='CHELMSFORD', max_length=10, unique=True, verbose_name='Position')),
                ('beginworktime', models.TimeField(blank=True, default='', verbose_name='Open Time')),
                ('overworktime', models.TimeField(blank=True, default='', verbose_name='Close time')),
                ('maxslot', models.PositiveIntegerField(default='2', verbose_name='Max Slot Num')),
                ('maxinbound', models.PositiveIntegerField(default='0', verbose_name='Max Inbound Num')),
                ('time_gap', models.IntegerField(default=30, verbose_name='Time Gap')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_warehouse_profile', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'db_table': 'WarehouseProfile',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryref', models.CharField(default='', max_length=25, verbose_name='Delivery Ref.')),
                ('workdate', models.DateField(default='', verbose_name='Date')),
                ('slottime', models.TimeField(default='', verbose_name='Time')),
                ('vehiclereg', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Vehicle Reg.')),
                ('status', models.CharField(default='INBOUND', max_length=8, verbose_name='In/Outbound')),
                ('progress', models.PositiveIntegerField(choices=[(1, 'Booked'), (2, 'Arrived'), (3, 'Loading'), (4, 'Finished'), (5, 'Abnormal')], default=1, verbose_name='Progress')),
                ('havetime', models.PositiveIntegerField(choices=[(1, 'YES, HAVE SLOT TIME'), (0, 'NO SLOT TIME')], default=1, verbose_name='Is Scheduled')),
                ('op_datetime', models.DateTimeField(blank=True, verbose_name='Operator')),
                ('remark', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Remark')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('hailerid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='haulier_warehouse', to='slot.haulier', verbose_name='Haulier')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_warehouse', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('position', models.ForeignKey(default='UK', on_delete=django.db.models.deletion.CASCADE, related_name='position_warehouse', to='slot.warehouseprofile', to_field='position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Slot List',
                'db_table': 'Warehouse',
                'unique_together': {('deliveryref',)},
            },
        ),
        migrations.CreateModel(
            name='SlotFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='File name')),
                ('files_profile', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='File profile')),
                ('local_file_name', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Local file name')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Upload DateTime')),
                ('is_void', models.BooleanField(default=0, verbose_name='Is Void')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('delivery_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.warehouse', verbose_name='Delivery Ref.')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_file_user', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Slot Files',
                'db_table': 'slot_files',
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryref', models.CharField(default='', max_length=25, verbose_name='Delivery Ref.')),
                ('progress', models.PositiveIntegerField(choices=[(1, 'Booked'), (2, 'Arrived'), (3, 'Loading'), (4, 'Finished'), (5, 'Abnormal')], default=1, verbose_name='Progress')),
                ('progress_name', models.CharField(blank=True, default='', max_length=10, verbose_name='Progress Name')),
                ('position', models.CharField(default='UK', max_length=10, verbose_name='Position')),
                ('remark', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Action')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('op_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_progressrecord', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'db_table': 'Progress_record',
            },
        ),
        migrations.AddField(
            model_name='haulier',
            name='position',
            field=models.ForeignKey(default='UK', on_delete=django.db.models.deletion.CASCADE, related_name='haulier_warehouse_position', to='slot.warehouseprofile', to_field='position', verbose_name='Haulier Position'),
        ),
        migrations.AlterUniqueTogether(
            name='haulier',
            unique_together={('code', 'position')},
        ),
        migrations.CreateModel(
            name='FixWeekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'MON'), (2, 'TUE'), (3, 'WED'), (4, 'TUR'), (5, 'FIR'), (6, 'SAT'), (7, 'SUN')], default=1, verbose_name='Weeks')),
                ('time', models.TimeField(blank=True, default='', verbose_name='Schedule Time')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Stop')], default=1, verbose_name='Status')),
                ('op_datetime', models.DateTimeField(auto_now=True, verbose_name='Operate Datetime')),
                ('Haulier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.haulier', verbose_name='Haulier Code (Name)')),
                ('op_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_fixweekday', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Haulier Scheduled Time',
                'db_table': 'Haulier_FixTime',
                'unique_together': {('Haulier', 'weekday', 'time')},
            },
        ),
    ]
