# Generated by Django 3.1 on 2020-08-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='hailer',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='hailerid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='warehouseprofile',
            name='beginworktime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouseprofile',
            name='overworktime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fixweekday',
            name='time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='maxinbound',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='maxslot',
            field=models.PositiveIntegerField(default='2'),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='op_user',
            field=models.CharField(default='Admin', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='fixweekday',
            unique_together={('hailer', 'weekday', 'time')},
        ),
    ]
