# Generated by Django 3.1 on 2020-08-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixweekday',
            old_name='op_user',
            new_name='op_id',
        ),
        migrations.RenameField(
            model_name='haulier',
            old_name='op_user',
            new_name='op_id',
        ),
        migrations.RenameField(
            model_name='progressrecord',
            old_name='op_user',
            new_name='op_id',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='op_user',
            new_name='op_id',
        ),
        migrations.RenameField(
            model_name='warehouseprofile',
            old_name='op_user',
            new_name='op_id',
        ),
        migrations.RemoveField(
            model_name='progressrecord',
            name='op_email',
        ),
        migrations.RemoveField(
            model_name='progressrecord',
            name='op_role',
        ),
        migrations.RemoveField(
            model_name='progressrecord',
            name='op_telephone',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='op_email',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='op_role',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='op_telephone',
        ),
    ]
