# Generated by Django 3.1 on 2020-09-25 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='File name')),
                ('save_path', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='File path')),
                ('file_type', models.PositiveIntegerField(choices=[(1, 'Delivery Manifest'), (0, 'Other')], default=1, verbose_name='FILE TYPE')),
                ('upload', models.DateTimeField(auto_now=True, verbose_name='Upload DateTime')),
                ('delivery_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.warehouse', verbose_name='Delivery Ref.')),
            ],
        ),
    ]
