# Generated by Django 3.1 on 2020-08-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haulier',
            name='email',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Email'),
        ),
    ]
