# Generated by Django 3.1 on 2020-09-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='File name')),
                ('file', models.FileField(upload_to='slot/')),
                ('file_type', models.PositiveIntegerField(choices=[(1, 'Delivery Manifest'), (0, 'Other')], default=1, verbose_name='FILE TYPE')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Upload DateTime')),
                ('delivery_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.warehouse', verbose_name='Delivery Ref.')),
            ],
            options={
                'verbose_name': 'Slot Files',
                'db_table': 'slot_files',
            },
        ),
    ]
