# Generated by Django 3.1 on 2020-08-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixweekday',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Stop')], default=1),
        ),
        migrations.AlterField(
            model_name='haulier',
            name='is_use',
            field=models.IntegerField(choices=[(1, 'Normal'), (0, 'Stop')], default=1),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='progress',
            field=models.PositiveIntegerField(choices=[(1, 'Booked'), (2, 'Arrived'), (3, 'Loading'), (4, 'Finished'), (5, 'Abnormal')], default=1),
        ),
    ]
