# Generated by Django 3.1 on 2020-08-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_auto_20200821_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haulier',
            name='contact',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='haulier',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
