# Generated by Django 3.1 on 2020-09-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_warehousefiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousefiles',
            options={'verbose_name': 'Delivery Files'},
        ),
        migrations.AlterModelTable(
            name='warehousefiles',
            table='warehouse_files',
        ),
    ]
