# Generated by Django 3.1.11 on 2021-05-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_auto_20210518_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haulier',
            name='code',
            field=models.CharField(default='', max_length=6, verbose_name='Code'),
        ),
    ]
