# Generated by Django 3.1 on 2020-08-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_auto_20200828_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='havetime',
            field=models.PositiveIntegerField(choices=[(1, 'YES, HAVE SLOT TIME'), (0, 'NO SLOT TIME')], default=1),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='progress',
            field=models.PositiveIntegerField(choices=[(1, 'Booked'), (2, 'Arrived'), (3, 'Loading'), (4, 'Finished'), (5, 'Abnormal')], default=1),
        ),
    ]
