# Generated by Django 3.1 on 2020-08-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_auto_20200821_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressrecord',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
