# Generated by Django 3.1 on 2020-10-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_slotfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotfiles',
            name='file',
        ),
        migrations.RemoveField(
            model_name='slotfiles',
            name='file_type',
        ),
        migrations.AddField(
            model_name='slotfiles',
            name='files_profile',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='File profile'),
        ),
        migrations.AddField(
            model_name='slotfiles',
            name='local_file_name',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Local file name'),
        ),
    ]
