# Generated by Django 3.1 on 2020-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_auto_20200816_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseprofile',
            name='beginworktime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='overworktime',
            field=models.TimeField(blank=True),
        ),
    ]
