# Generated by Django 3.1 on 2020-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_auto_20200821_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haulier',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Telephone'),
        ),
    ]
