# Generated by Django 3.1 on 2020-09-02 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slot', '0003_auto_20200828_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixweekday',
            options={'verbose_name': 'Haulier Scheduled Time'},
        ),
        migrations.AlterModelOptions(
            name='haulier',
            options={'verbose_name': 'Haulier List'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Slot List'},
        ),
        migrations.AddField(
            model_name='warehouse',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='fixweekday',
            name='Haulier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.haulier', verbose_name='Haulier Code (Name)'),
        ),
        migrations.AlterField(
            model_name='fixweekday',
            name='op_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
        migrations.AlterField(
            model_name='fixweekday',
            name='op_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_fixweekday', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='fixweekday',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Stop')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fixweekday',
            name='time',
            field=models.TimeField(blank=True, default='', verbose_name='Schedule Time'),
        ),
        migrations.AlterField(
            model_name='fixweekday',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'MON'), (2, 'TUE'), (3, 'WED'), (4, 'TUR'), (5, 'FIR'), (6, 'SAT'), (7, 'SUN')], default=1, verbose_name='Weeks'),
        ),
        migrations.AlterField(
            model_name='haulier',
            name='code',
            field=models.CharField(default='', max_length=4, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='haulier',
            name='contact',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='haulier',
            name='is_use',
            field=models.IntegerField(choices=[(1, 'Normal'), (0, 'Stop')], default=1, verbose_name='Is Normal'),
        ),
        migrations.AlterField(
            model_name='haulier',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='haulier',
            name='op_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
        migrations.AlterField(
            model_name='haulier',
            name='op_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_haulier', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='deliveryref',
            field=models.CharField(default='', max_length=25, verbose_name='Delivery Ref.'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='op_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='op_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_progressrecord', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='position',
            field=models.CharField(default='UK', max_length=2, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='progress',
            field=models.PositiveIntegerField(choices=[(1, 'Booked'), (2, 'Arrived'), (3, 'Loading'), (4, 'Finished'), (5, 'Abnormal')], default=1, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='progress_name',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Progress Name'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='deliveryref',
            field=models.CharField(default='', max_length=25, verbose_name='Delivery Ref.'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='hailerid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='haulier_warehouse', to='slot.haulier', verbose_name='Haulier'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='havetime',
            field=models.PositiveIntegerField(choices=[(1, 'YES, HAVE SLOT TIME'), (0, 'NO SLOT TIME')], default=1, verbose_name='Is Scheduled'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='op_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='op_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_warehouse', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='position',
            field=models.CharField(default='UK', max_length=2, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='progress',
            field=models.PositiveIntegerField(choices=[(1, 'Booked'), (2, 'Arrived'), (3, 'Loading'), (4, 'Finished'), (5, 'Abnormal')], default=1, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='slottime',
            field=models.TimeField(default='', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(default='INBOUND', max_length=8, verbose_name='In/Outbound'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='vehiclereg',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Vehicle Reg.'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='workdate',
            field=models.DateField(default='', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='beginworktime',
            field=models.TimeField(blank=True, default='', verbose_name='Open Time'),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='maxinbound',
            field=models.PositiveIntegerField(default='0', verbose_name='Max Inbound Num'),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='maxslot',
            field=models.PositiveIntegerField(default='2', verbose_name='Max Slot Num'),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='op_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Operate Datetime'),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='op_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_warehouseprofile', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='overworktime',
            field=models.TimeField(blank=True, default='', verbose_name='Close time'),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='position',
            field=models.CharField(default='UK', max_length=2, verbose_name='Position'),
        ),
    ]
