# Generated by Django 3.1 on 2020-08-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_auto_20200821_0839'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('deliveryref',)},
        ),
    ]
