# Generated by Django 3.1 on 2020-09-25 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_auto_20200925_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousefiles',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='slot/'),
            preserve_default=False,
        ),
    ]
