# Generated by Django 3.1 on 2020-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_auto_20201001_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotfiles',
            name='is_void',
            field=models.BooleanField(default=0, verbose_name='Is Void'),
        ),
    ]
