# Generated by Django 3.1 on 2020-08-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_auto_20200816_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='haulier',
            name='is_use',
            field=models.IntegerField(default=1),
        ),
    ]
