# Generated by Django 3.1 on 2020-09-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0004_warehousefiles_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousefiles',
            old_name='upload',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='warehousefiles',
            name='delivery_ref',
        ),
        migrations.RemoveField(
            model_name='warehousefiles',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='warehousefiles',
            name='save_path',
        ),
        migrations.AlterField(
            model_name='warehousefiles',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
