# Generated by Django 3.1 on 2020-08-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0004_auto_20200821_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
