# Generated by Django 3.1 on 2020-08-17 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0004_haulier_is_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='haulier',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='haulier',
            name='email',
            field=models.CharField(blank=True, max_length=250, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='haulier',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telephone'),
        ),
    ]
