# Generated by Django 3.1 on 2020-08-22 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slot', '0004_auto_20200821_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixweekday',
            name='op_id',
        ),
        migrations.RemoveField(
            model_name='haulier',
            name='op_id',
        ),
        migrations.RemoveField(
            model_name='progressrecord',
            name='op_id',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='op_id',
        ),
        migrations.RemoveField(
            model_name='warehouseprofile',
            name='op_id',
        ),
        migrations.AddField(
            model_name='fixweekday',
            name='op_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_fixweekday', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='haulier',
            name='op_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_haulier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='op_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_progressrecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='op_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_warehouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouseprofile',
            name='op_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='op_warehouseprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fixweekday',
            name='time',
            field=models.TimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='slottime',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='workdate',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='beginworktime',
            field=models.TimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='warehouseprofile',
            name='overworktime',
            field=models.TimeField(blank=True, default=''),
        ),
    ]
