# Generated by Django 3.1 on 2020-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0004_slotfiles_is_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotfiles',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
