# Generated by Django 3.1 on 2020-09-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0004_auto_20200902_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='op_datetime',
            field=models.DateTimeField(blank=True, verbose_name='Operator'),
        ),
    ]
