# Generated by Django 3.1 on 2020-08-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0005_auto_20200817_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
