# Generated by Django 3.1 on 2020-09-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0005_auto_20200925_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WarehouseFiles',
            new_name='SlotFiles',
        ),
    ]
