# Generated by Django 3.1 on 2020-08-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0005_auto_20200821_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='hailerid',
            new_name='haulierid',
        ),
    ]
