# Generated by Django 3.1 on 2020-09-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0006_auto_20200925_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotfiles',
            options={'verbose_name': 'Slot Files'},
        ),
        migrations.AlterModelTable(
            name='slotfiles',
            table='slot_files',
        ),
    ]
