# Generated by Django 3.1 on 2020-08-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0006_auto_20200821_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='haulierid',
            new_name='hailerid',
        ),
    ]
