# Generated by Django 3.1 on 2020-09-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Menu Name')),
                ('menu_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='Remark')),
            ],
            options={
                'verbose_name': 'First Menu',
                'db_table': 'z_first_menu',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Menu Name')),
                ('menu_url', models.CharField(blank=True, default='', max_length=200, verbose_name='Menu URL')),
                ('menu_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='Remark')),
                ('first_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_menu', to='menu.firstmenu', verbose_name='First Menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'db_table': 'z_menu',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, default='', max_length=20, verbose_name='Role Name')),
                ('role_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='Remark')),
            ],
            options={
                'verbose_name': 'Role',
                'db_table': 'z_role',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_display', models.BooleanField(default=True, verbose_name='is_display_first_menu')),
                ('is_list', models.BooleanField(default=True, verbose_name='is_List')),
                ('is_update', models.BooleanField(default=True, verbose_name='is_Update')),
                ('is_delete', models.BooleanField(default=True, verbose_name='is_Delete')),
                ('first_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_first_menu', to='menu.firstmenu', verbose_name='First Menu')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_menu', to='menu.menu', verbose_name='Menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_role', to='menu.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Permission',
                'db_table': 'z_permission',
            },
        ),
    ]
