# Generated by Django 3.1.11 on 2021-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_order', models.CharField(blank=True, default='', max_length=50, verbose_name='Menu Order')),
                ('menu_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Menu Name')),
                ('node_type', models.PositiveSmallIntegerField(choices=[(1, 'WEB PAGE'), (2, 'BUTTON'), (3, 'FILE FOLDER')], default=1, verbose_name='node_type')),
                ('menu_url', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Menu URL')),
                ('menu_icon', models.CharField(blank=True, default='', max_length=200, verbose_name='Icon URl')),
                ('parent_id', models.PositiveSmallIntegerField(default=0, verbose_name='Parent ID')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='Level')),
                ('path', models.CharField(blank=True, default='', max_length=200, verbose_name='Path')),
                ('is_use', models.BooleanField(default=True, verbose_name='is_use')),
            ],
            options={
                'verbose_name': 'Menu',
                'db_table': 'z_menu',
            },
        ),
    ]
