# Generated by Django 3.1 on 2020-09-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmenu',
            name='menu_order',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Menu Order'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_order',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Menu Order'),
        ),
    ]
