# Generated by Django 3.1 on 2020-09-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200904_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmenu',
            name='menu_url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Menu URL'),
        ),
    ]
