# Generated by Django 3.1 on 2020-09-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_firstmenu_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmenu',
            name='have_child',
            field=models.BooleanField(default=True, verbose_name='have_child'),
        ),
    ]
