# Generated by Django 3.1 on 2020-09-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_firstmenu_have_child'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Second Menu'},
        ),
    ]
