# Generated by Django 3.1 on 2020-09-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200904_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='first_menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_remark',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='first_menu',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_display',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_list',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_update',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_use',
            field=models.BooleanField(default=True, verbose_name='is_use'),
        ),
        migrations.AddField(
            model_name='menu',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_icon',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Icon URl'),
        ),
        migrations.AddField(
            model_name='menu',
            name='node_type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='node_type'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent_id',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Parent ID'),
        ),
        migrations.AddField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Menu URL'),
        ),
        migrations.DeleteModel(
            name='FirstMenu',
        ),
    ]
